---
micronaut:
    application:
        name: mongo-test

#Uncomment to set server port
#    server:
#        port: 8080

---
mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/micronaut
