---
micronaut:
    application:
        name: mongo-test

jackson:
    serialization:
        writeDatesAsTimestamps: false

#Uncomment to set server port
#    server:
#        port: 8080

grails:
    mongodb:
        databaseName: micronaut

mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
