---
micronaut:
    application:
        name: mongo-test

jackson:
    serialization:
        writeDatesAsTimestamps: false

grails:
    mongodb:
        databaseName: micronaut

mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
