---
micronaut:
    application:
        name: mongo-test
    executors:
        io:
            type: fixed
            nThreads: 10

jackson:
    serialization:
        writeDatesAsTimestamps: false

grails:
    mongodb:
        databaseName: micronaut-mongo-gorm-example

mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
